source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UIMessageView_Example', :exclusive => true do
  pod "UIMessageView", :path => "../"
end

target 'UIMessageView_Tests', :exclusive => true do
  pod "UIMessageView", :path => "../"

  
end
